language: node_js
node_js:
  - "0.10"
  - "0.8"
  - "0.6"
before_script:
  - "git submodule update --init"
  - "phantomjs test/phantomjs-index.js"
#notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#example"
